type Movie = {
    funcDescription?: string;
    title: string;
    description: string;
    imageUrl: string;
    imdbLink: string;
}

type MovieRecs = Record<string, Movie[]>;


export const recoMovies: MovieRecs = {
    Ni: [
        { funcDescription: `Ni is focused on future possibilities and abstract concepts. It seeks to understand the underlying meaning and patterns behind events. Ni users often have a strong sense of foresight and can see how things will unfold over time. They are adept at synthesizing information from various sources to form a cohesive vision of the future. Ni users may appear mysterious or enigmatic to others due to their deep, introspective nature and their ability to perceive hidden connections.`, title: 'Paprika', description: `When a machine that allows therapists to enter their patients' dreams is stolen, all hell breaks loose. Only a young female therapist, Paprika, can stop it.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/bLUUr474Go1DfeN1HLjE3rnZXBq.jpg`, imdbLink: `https://www.imdb.com/title/tt0851578/` },
        { title: 'The Matrix', description: `When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg`, imdbLink: `https://www.imdb.com/title/tt0133093/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_the%2520matrix` },
        { title: 'Interstellar', description: `When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`, imdbLink: `https://www.imdb.com/title/tt0816692/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_interste` },
        { title: 'Lost In Translation', description: `A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/4k4Yz08WGfbu8ITIjaG99XTeco8.jpg`, imdbLink: `https://www.imdb.com/title/tt0335266/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_lost%2520in%2520` }
    ],
    Ne: [
        { funcDescription: `Ne is all about exploring multiple possibilities and ideas. It thrives on novelty and innovation, constantly seeking new connections and patterns. Ne users are often imaginative and enjoy brainstorming and thinking outside the box. They are quick to see potential in various situations and are skilled at generating creative solutions. Ne users may sometimes struggle with focusing on one idea for too long, as they are always eager to explore new avenues and possibilities.`, title: 'The Secret Life of Walter Mitty', description: `When both he and a colleague are about to lose their job, Walter takes action by embarking on an adventure more extraordinary than anything he ever imagined.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tY6ypjKOOtujhxiSwTmvA4OZ5IE.jpg`, imdbLink: `https://www.imdb.com/title/tt0359950/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_the%2520secret%2520life%2520of` },
        { title: 'Midnight in Paris', description: `While on a trip to Paris with his fiancée's family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s every day at midnight.`, imageUrl: `https://image.tmdb.org/t/p/original/4wBG5kbfagTQclETblPRRGihk0I.jpg`, imdbLink: `https://www.imdb.com/title/tt1605783/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Midnight%2520in%2520Paris` },
        { title: 'Pulp Fiction', description: `The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg`, imdbLink: `https://www.imdb.com/title/tt0110912/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_Pulp%2520Fiction` },
        { title: 'Spirited Away', description: `During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg`, imdbLink: `https://www.imdb.com/title/tt0245429/?ref_=fn_al_tt_1` }
    ],
    Ti: [
        { funcDescription: `Ti is concerned with internal logical consistency and understanding the underlying principles of systems. It seeks to categorize and analyze information to build a coherent framework. Ti users are often analytical and enjoy solving complex problems. They value precision and clarity in their thinking and are driven by a desire to understand how things work. Ti users may come across as detached or impersonal, as they prioritize objective analysis over emotional considerations.`, title: 'Good Will Hunting', description: `Will Hunting, a janitor at MIT, has a gift for mathematics, but needs help from a psychologist to find direction in his life.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg`, imdbLink: `https://www.imdb.com/title/tt0119217/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Good%2520Will%2520Hunting` },
        { title: 'Ghost in the Shell', description: `A cyborg policewoman and her partner hunt a mysterious and powerful hacker called the Puppet Master.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9gC88zYUBARRSThcG93MvW14sqx.jpg`, imdbLink: `https://www.imdb.com/title/tt0113568/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_Ghost%2520in%2520the%2520Shell` },
        { title: 'The Imitation Game', description: `During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians while attempting to come to terms with his troubled private life.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg`, imdbLink: `https://www.imdb.com/title/tt2084970/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_The%2520Imitation%2520Game` },
        { title: 'Ex Machina', description: `A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aeJS3OXnp7d17QSoMdglZERwCkM.jpg`, imdbLink: `https://www.imdb.com/title/tt0470752/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_ex%2520mac` }
    ],
    Te: [
        { funcDescription: `Te focuses on external efficiency and organization. It seeks to implement logical systems and structures to achieve goals effectively. Te users are often pragmatic and enjoy managing projects and making decisions based on objective criteria. They are skilled at organizing resources and people to accomplish tasks and are driven by a desire for tangible results. Te users may sometimes be perceived as demanding or overly focused on productivity, as they prioritize efficiency and effectiveness.`, title: 'The Social Network', description: `As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea and by the co-founder who was later squeezed out of the business.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg`, imdbLink: `https://www.imdb.com/title/tt1285016/?ref_=fn_al_tt_1` },
        { title: 'Moneyball', description: `Oakland A's general manager Billy Beane's successful attempt to assemble a baseball team on a lean budget by employing computer-generated analysis to acquire new players.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/myRHYxfLpgwwRd13kcrRqxG6jAj.jpg`, imdbLink: `https://www.imdb.com/title/tt1210166/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Moneyball` },
        { title: 'Pride and Prejudice', description: `A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages.`, imageUrl: `https://image.tmdb.org/t/p/w600_and_h900_bestv2/sGjIvtVvTlWnia2zfJfHz81pZ9Q.jpg`, imdbLink: `https://www.imdb.com/title/tt0414387/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Pride%2520and%2520Prejudice` },
        { title: 'The Wolf of Wall Street', description: `Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg`, imdbLink: `https://www.imdb.com/title/tt0993846/?ref_=nv_sr_srsg_0_tt_5_nm_3_in_0_q_The%2520Wolf%2520of%2520Wall%2520Street` }
    ],
    Fi: [
        { funcDescription: `Fi is centered on internal values and personal authenticity. It seeks to understand and stay true to one’s own moral compass. Fi users are often empathetic and value deep, meaningful connections with others. They are guided by a strong sense of right and wrong and are driven by a desire to live in accordance with their principles. Fi users may appear reserved or private, as they are deeply introspective and selective about sharing their inner world with others.`, title: 'Into the Wild', description: `After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2MSGZEE6XZd2r4ODNziwAw7Hpw0.jpg`, imdbLink: `https://www.imdb.com/title/tt0758758/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Into%2520the%2520Wild` },
        { title: 'Your Name', description: `Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vfJFJPepRKapMd5G2ro7klIRysq.jpg`, imdbLink: `https://www.imdb.com/title/tt5311514/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_your%2520n` },
        { title: 'Eternal Sunshine of the Spotless Mind', description: `When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg`,imdbLink: `https://www.imdb.com/title/tt0338013/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Eternal%2520Sunshine%2520of%2520the%2520Spotless%2520Min` },
        { title: 'Dead Poets Society', description: `Maverick teacher John Keating returns in 1959 to the prestigious New England boys' boarding school where he was once a star student, using poetry to embolden his pupils to new heights of self-expression.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hmGAF5NDoYB6S39UONevjHCESOI.jpg`, imdbLink: `https://www.imdb.com/title/tt0097165/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Dead%2520Poets%2520Society` }
    ],
    Fe: [
        { funcDescription: `Fe is concerned with external harmony and social dynamics. It seeks to create and maintain positive relationships and social cohesion. Fe users are often attuned to the emotions of others and enjoy fostering a sense of community. They are skilled at reading social cues and are driven by a desire to create a harmonious environment. Fe users may sometimes struggle with setting boundaries, as they prioritize the needs and feelings of others over their own.`, title: 'The Notebook', description: `An elderly man reads to a woman with dementia the story of two young lovers whose romance is threatened by the difference in their respective social classes.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg`, imdbLink: `https://www.imdb.com/title/tt0332280/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_the%2520no` },
        { title: 'The Pursuit of Happyness', description: `A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg`, imdbLink: `https://www.imdb.com/title/tt0454921/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_the%2520purs` },
        { title: 'The Blind Side', description: `The story of Michael Oher, a homeless and traumatized boy who became an All-American football player and first-round NFL draft pick with the help of a caring woman and her family.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bMgq7VBriuBFknXEe9E9pVBYGZq.jpg`, imdbLink: `https://www.imdb.com/title/tt0878804/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520blin` },
        { title: 'Wolf Children', description: `After her werewolf lover unexpectedly dies in an accident while hunting for food for their children, a young woman must find ways to raise the werewolf son and daughter that she had with him while keeping their trait hidden from society.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3Nllh6JgcrFdtOn6iFOWHudNInd.jpg`, imdbLink: `https://www.imdb.com/title/tt2140203/?ref_=nv_sr_srsg_0_tt_4_nm_4_in_0_q_wolf%2520ch` }
    ],
    Si: [
        { funcDescription: `Si focuses on past experiences and sensory details. It seeks to preserve and recall information based on personal history and familiarity. Si users are often detail-oriented and value tradition and stability. They are skilled at noticing subtle changes in their environment and are driven by a desire for consistency and reliability. Si users may sometimes be resistant to change, as they prefer to rely on tried-and-true methods and experiences.`, title: 'The Lord of the Rings: The Fellowship of the Ring', description: `A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg`, imdbLink: `https://www.imdb.com/title/tt0120737/?ref_=nv_sr_srsg_0_tt_6_nm_2_in_0_q_The%2520Lord%2520of%2520the%2520Rings%253A%2520The%2520Fello` },
        { title: 'Star Wars: Episode IV - A New Hope', description: `Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg`, imdbLink: `https://www.imdb.com/title/tt0076759/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_Star%2520Wars%253A%2520Episode%2520IV%2520-%2520A%2520New%2520` },
        { title: 'The Sound of Music', description: `A young novice is sent by her convent in 1930s Austria to become a governess to the seven children of a widowed naval officer.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5qQTu2iGTiQ2UvyGp0beQAZ2rKx.jpg`, imdbLink: `https://www.imdb.com/title/tt0059742/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_the%2520soun` },
        { title: 'Forrest Gump', description: `The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg`, imdbLink: `https://www.imdb.com/title/tt0109830/?ref_=nv_sr_srsg_0_tt_1_nm_7_in_0_q_forres` }
    ],
    Se: [
        { funcDescription: `Se is all about engaging with the present moment and the external environment. It seeks to experience life through direct sensory input and action. Se users are often spontaneous and enjoy taking risks and seeking new experiences. They are skilled at reacting quickly to changes in their surroundings and are driven by a desire for excitement and adventure. Se users may sometimes struggle with long-term planning, as they prioritize immediate experiences and gratification.`, title: 'Fight Club', description: `An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg`, imdbLink: `https://www.imdb.com/title/tt0137523/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_fught` },
        { title: 'Taxi Driver', description: `A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.`, imageUrl: `https://i0.wp.com/cinemadebate.com/wp-content/uploads/2023/02/26d731f6-400d-4d84-a083-3792338ca6d7.jpg?w=1000&ssl=1`, imdbLink: `https://www.imdb.com/title/tt0075314/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_taxi` },
        { title: 'The Revenant', description: `A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tSaBkriE7TpbjFoQUFXuikoz0dF.jpg`, imdbLink: `https://www.imdb.com/title/tt1663202/?ref_=fn_al_tt_1` },
        { title: 'Dunkirk', description: `Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.`, imageUrl: `https://www.themoviedb.org/t/p/w600_and_h900_bestv2/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg`, imdbLink: `https://www.imdb.com/title/tt5013056/?ref_=nv_sr_srsg_3_tt_7_nm_1_in_0_q_dunki` }
    ]
}


